### ISSUE TITLE
Pandasgui has started for 2 seconds and got closed without any action

### ISSUE THREAD

**Issue by squeezer44** [adamerose/pandasgui#54] opened 2020-10-24 21:18 UTC
Hi,

I'm trying to use pandasgui with this constellation:

OS: Windows 10
pandasgui==0.2.5.1
plotly==4.11.0
PyQt5==5.15.0
PyQt5-sip==12.8.0
PyQtWebEngine==5.15.1

and with this Python script:

```
import pandas as pd
from pandasgui import show


df = pd.DataFrame(([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=['a', 'b', 'c'])

show(df)
```

- Expected result
PandasGUI has opened and df can be analysed

- Given result
An empty pandasgui window was opened for 2 seconds, closed without any further actions. No error message - nothing.
The output in the console:
```
Process returned 0 (0x0)        execution time : 3.395 s
```

**Comment by adamerose** [comment] 2020-10-25 13:14
I'm assuming you're running that code as a script, not in IPython right? I think this is a duplicate of #49

However I did just improve the default behavior so pandasgui will detect whether you ran it in an interactive console, and adjust settings to block or not without you needing to specify any settings. Can you update to pandasgui version 0.2.7 and verify whether your problem is fixed

**Closed by adamerose** 2020-10-25 13:14 UTC
Labels: bug

**Comment by squeezer44** [comment] 2020-10-25 18:03
@adamerose 

Thx - you've made my day: expected result = given result 💯 
both as a sript in the Python console and as a cell inside a Jupyter Notebook.

First I've uninstalled my local pandasgui==0.2.5.1. After that I've installed your fixed version from your GithubRepo and it works fine.

I did the test (Python console and Jupyter notebook) 

OS: Windows 10
pandasgui @ git+https://github.com/adamerose/pandasgui.git@7c631616979a0783f7ab3cb36b82f5772ce2b3b6
plotly==4.12.0
PyQt5==5.15.1
PyQt5-sip==12.8.0
PyQtWebEngine==5.15.1

Thx a lot!
