### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by Lolologist** [adamerose/pandasgui#58] opened 2020-10-29 05:36 UTC
Problem: dataframes containing a column with entries of type List fail to load.

Step to reproduce: try to show() a pandas dataframe where one column is all, or has some, List objects in it.

Expected Behavior: window shows with data instead of blank.

**Comment by adamerose** [comment] 2020-10-29 06:10
Duplicate of #58, are you sure you have the latest version?

![image](https://user-images.githubusercontent.com/10884874/97532049-e77fe800-198b-11eb-9701-1bcdf1887b27.png)

**Closed** 2020-11-01 07:02 UTC
Labels: bug
