### ISSUE TITLE
ImportError undefined symbol k5_buf_data

### ISSUE THREAD

**Issue by danschef** [adamerose/pandasgui#50] opened 2020-10-22 18:36 UTC
I created a new test environment as follows:

```bash
conda create -n pandasgui_test python=3.8
conda install jupyter
pip install pandasgui
```

Then I ran this from a Jupyter-Notebook:

```python
from pandasgui import show
import numpy as np
df = DataFrame(np.random.randint(0, 100, (100, 150)))
show(df)
```

which raises:

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-65274c620237> in <module>
----> 1 from pandasgui import show
      2 import numpy as np
      3 df = DataFrame(np.random.randint(0, 100, (100, 150)))
      4 show(df)

~/miniconda3/envs/pandasgui_test/lib/python3.8/site-packages/pandasgui/__init__.py in <module>
----> 1 from pandasgui.gui import show
      2 
      3 __all__ = ["show"]

~/miniconda3/envs/pandasgui_test/lib/python3.8/site-packages/pandasgui/gui.py in <module>
     12 from pandasgui.store import Store, PandasGuiDataFrame
     13 from pandasgui.utility import fix_ipython, fix_pyqt, get_logger, as_dict, delete_datasets
---> 14 from pandasgui.widgets.dataframe_explorer import DataFrameExplorer
     15 from pandasgui.widgets.find_toolbar import FindToolbar
     16 from pandasgui.widgets.json_viewer import JsonViewer

~/miniconda3/envs/pandasgui_test/lib/python3.8/site-packages/pandasgui/widgets/dataframe_explorer.py in <module>
      7 from pandasgui.utility import get_logger, nunique
      8 from pandasgui.widgets.dataframe_viewer import DataFrameViewer
----> 9 from pandasgui.widgets.grapher import Grapher
     10 from pandasgui.widgets.reshaper import Reshaper
     11 from pandasgui.widgets.filter_viewer import FilterViewer

~/miniconda3/envs/pandasgui_test/lib/python3.8/site-packages/pandasgui/widgets/grapher.py in <module>
     13 
     14 from pandasgui.utility import flatten_df, get_logger
---> 15 from pandasgui.widgets.plotly_viewer import PlotlyViewer
     16 from pandasgui.widgets.spinner import Spinner
     17 from pandasgui.widgets.dragger import Dragger, ColumnArg, Schema

~/miniconda3/envs/pandasgui_test/lib/python3.8/site-packages/pandasgui/widgets/plotly_viewer.py in <module>
     27         app.__init__(sys.argv)
     28     else:
---> 29         raise e
     30 
     31 

~/miniconda3/envs/pandasgui_test/lib/python3.8/site-packages/pandasgui/widgets/plotly_viewer.py in <module>
     15 # https://stackoverflow.com/a/57436077/3620725
     16 try:
---> 17     from PyQt5 import QtWebEngineWidgets
     18 except ImportError as e:
     19     if e.msg == "QtWebEngineWidgets must be imported before a QCoreApplication instance is created":

ImportError: /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2: symbol k5_buf_data, version krb5support_0_MIT not defined in file libkrb5support.so.0 with link time reference
```

**Comment by adamerose** [comment] 2020-10-24 12:17
Looks like a problem with your PyQt5 installation. Closing since it's not specific to PandasGUI (you should be able to reproduce the error by running only `from PyQt5 import QtWebEngineWidgets`, let me know if this isn't the case)

My only advice is reinstall things
```
pip uninstall -y PyQt5 PyQtWebEngine PyQt5-sip
pip install PyQt5 PyQtWebEngine PyQt5-sip
```

**Closed by adamerose** 2020-10-24 12:17 UTC
