### ISSUE TITLE
GUI Window opening and closing immediately

### ISSUE THREAD

**Issue by Mossa-D** [adamerose/pandasgui#49] opened 2020-10-22 09:06 UTC
Hello there.

I tried running the example code. When it runs, the pandasGUI opens and closes immediately.
I don't have much to add unfortunately.

```
import pandas as pd
from pandasgui import show

df = pd.DataFrame(([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=['a', 'b', 'c'])
show(df)
```

Packages used :
pandasgui 0.2.5.1
pandas 1.1.3
pip 20.2.4
python 3.8.6 x64
Pycharm 2020.2.1

Windows 10

**Comment by adamerose** [comment] 2020-10-22 09:10
Duplicate of #37

(Unless it still happens in IPython, then that's a bug and you can reopen)

**Closed by adamerose** 2020-10-22 09:10 UTC

**Comment by Mossa-D** [comment] 2020-10-22 09:21
It worked, thank you.

I apologize, I forgot to check the closed issues before posting.

Have a nice day.
