### ISSUE TITLE
Error at import: from pandasgui import show

### ISSUE THREAD

**Issue by gitjoost** [adamerose/PandasGUI#151] opened 2021-06-26 16:53 UTC
At point of import "from pandasgui import show" following error is generated:
  File ".venv/lib/python3.8/site-packages/pandasgui/__init__.py", line 15, in <module>
    from pandasgui.gui import show
  File ".venv/lib/python3.8/site-packages/pandasgui/gui.py", line 17, in <module>
    from pandasgui.widgets.navigator import Navigator
  File ".venv/lib/python3.8/site-packages/pandasgui/widgets/navigator.py", line 23, in <module>
    import mouse
  File ".venv/lib/python3.8/site-packages/mouse/__init__.py", line 56, in <module>
    raise OSError("Unsupported platform '{}'".format(_platform.system()))
OSError: Unsupported platform 'Darwin'

**Environment**
OS: macOS 11.3
Python: 3.8.1
IDE: VSCode, Terminal

**Package versions**  
ipython==7.25.0
ipython-genutils==0.2.0
pandasgui==0.2.11
plotly==5.0.0
PyQt5==5.15.4
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.0
PyQtWebEngine==5.15.4
PyQtWebEngine-Qt5==5.15.2

**Comment by adamerose** [comment] 2021-06-26 20:41
Duplicate of #145, this should be fixed in release 0.2.12

**Closed by adamerose** 2021-06-26 20:41 UTC
Labels: bug
