### ISSUE TITLE
0.2.12 casts pd.Int32Dtype() to float64

### ISSUE THREAD

**Issue by rjsdotorg** [adamerose/PandasGUI#152] opened 2021-07-01 23:56 UTC
**0.2.12 casts pd.Int32Dtype() to float64**  
![Clipboard01](https://user-images.githubusercontent.com/20799053/124201431-e0febe80-da8c-11eb-84db-4d3eff263ca1.jpg)

**Environment**
OS: Windows 7
Python:  3.8.2

**Package versions**  
ipython==7.15.0
ipython-genutils==0.2.0
jupyter-client==6.1.3
jupyter-core==4.6.3
jupyterlab==2.1.4
jupyterlab-server==1.1.5
notebook==6.0.3
pandasgui @ file:///C:/Users/Ray/Desktop/PandasGUI-develop.zip
plotly==4.14.3
PyQt5==5.15.4
PyQt5-Qt5==5.15.2
PyQt5-sip==12.8.0
PyQtWebEngine==5.15.4
PyQtWebEngine-Qt5==5.15.2

In addition, runs fine when opening:
`PandasGUI INFO — pandasgui.gui — Opening PandasGUI`

but when closing the GUI I get:

```
[8684:4300:0701/165045.388:ERROR:gles2_cmd_decoder.cc(18938)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCre
ateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[8684:4300:0701/165045.390:ERROR:gles2_cmd_decoder.cc(18959)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeg
inSharedImageAccessCHROMIUM: bound texture is not a shared image
[8684:4300:0701/165045.394:ERROR:gles2_cmd_decoder.cc(10716)] [.DisplayCompositor]RENDER WARNING: texture bound to textu
re unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[8684:4300:0701/165045.402:ERROR:gles2_cmd_decoder.cc(18988)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEnd
SharedImageAccessCHROMIUM: bound texture is not a shared image
[8684:4300:0701/165045.403:ERROR:gles2_cmd_decoder.cc(18938)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCre
ateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[8684:4300:0701/165045.416:ERROR:gles2_cmd_decoder.cc(18959)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeg
inSharedImageAccessCHROMIUM: bound texture is not a shared image
[8684:4300:0701/165045.420:ERROR:gles2_cmd_decoder.cc(10716)] [.DisplayCompositor]RENDER WARNING: texture bound to textu
re unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[8684:4300:0701/165045.438:ERROR:gles2_cmd_decoder.cc(18988)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEnd
SharedImageAccessCHROMIUM: bound texture is not a shared image
[8684:4300:0701/165045.445:ERROR:gles2_cmd_decoder.cc(18938)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCre
ateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[8684:4300:0701/165045.448:ERROR:gles2_cmd_decoder.cc(18959)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeg
inSharedImageAccessCHROMIUM: bound texture is not a shared image
[8684:4300:0701/165045.451:ERROR:gles2_cmd_decoder.cc(10716)] [.DisplayCompositor]RENDER WARNING: texture bound to textu
re unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[8684:4300:0701/165045.455:ERROR:gles2_cmd_decoder.cc(18988)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEnd
SharedImageAccessCHROMIUM: bound texture is not a shared image
[8684:4300:0701/165045.472:ERROR:gles2_cmd_decoder.cc(18938)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCre
ateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[8684:4300:0701/165045.475:ERROR:gles2_cmd_decoder.cc(18959)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeg
inSharedImageAccessCHROMIUM: bound texture is not a shared image
[8684:4300:0701/165045.479:ERROR:gles2_cmd_decoder.cc(10716)] [.DisplayCompositor]RENDER WARNING: texture bound to textu
re unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[8684:4300:0701/165045.482:ERROR:gles2_cmd_decoder.cc(18988)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEnd
SharedImageAccessCHROMIUM: bound texture is not a shared image
[8684:4300:0701/165045.485:ERROR:gles2_cmd_decoder.cc(18938)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCre
ateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[8684:4300:0701/165045.489:ERROR:gles2_cmd_decoder.cc(18959)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeg
inSharedImageAccessCHROMIUM: bound texture is not a shared image
[8684:4300:0701/165045.513:ERROR:gles2_cmd_decoder.cc(10716)] [.DisplayCompositor]RENDER WARNING: texture bound to textu
re unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[8684:4300:0701/165045.516:ERROR:gles2_cmd_decoder.cc(18988)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEnd
SharedImageAccessCHROMIUM: bound texture is not a shared image
[8684:4300:0701/165045.520:ERROR:gles2_cmd_decoder.cc(18938)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoCre
ateAndTexStorage2DSharedImageINTERNAL: invalid mailbox name
[8684:4300:0701/165045.539:ERROR:gles2_cmd_decoder.cc(18959)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoBeg
inSharedImageAccessCHROMIUM: bound texture is not a shared image
[8684:4300:0701/165045.542:ERROR:gles2_cmd_decoder.cc(10716)] [.DisplayCompositor]RENDER WARNING: texture bound to textu
re unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?
[8684:4300:0701/165045.546:ERROR:gles2_cmd_decoder.cc(18988)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : DoEnd
SharedImageAccessCHROMIUM: bound texture is not a shared image
```

**Comment by adamerose** [comment] 2021-07-02 13:26
I'm unable to reproduce:
![image](https://user-images.githubusercontent.com/10884874/124281006-4d260480-db17-11eb-8e70-4a52a0b75252.png)

Can you share the CSV and code that results in your problem?

**Comment by rjsdotorg** [comment] 2021-07-02 15:11
Shoot, I think the re-cast problem is my bad
`df = pandas.read_csv('df_tmp.csv')`
creates float64s.
Should I delete this issue?
I do still get GUI errors after closing the latest version - I could make another for that.

**Comment by adamerose** [comment] 2021-07-02 15:18
@rjsdotorg No problem yeah I'll close this, make a new one for the other problem (which seems to be Chromium logs from the embedded web browser used for the Grapher, we can discuss in the new issue)

**Closed by adamerose** 2021-07-02 15:18 UTC
Labels: bug
